version: '3'

services:
  site:
    image: jekyll/jekyll:3.8.6
    command: jekyll serve --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - ruby_bundle:/usr/local/bundle

volumes:
  ruby_bundle: